# Generated by Django 5.0.1 on 2024-01-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_alter_category_categoryname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_listings",
            name="img_product",
            field=models.CharField(max_length=604),
        ),
    ]
