# Generated by Django 5.0.1 on 2024-02-03 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_watchlist"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="watchlist",
            unique_together={("user", "product")},
        ),
    ]
